apiVersion: v1
appVersion: 0.3.2
description: Metrics Server is a cluster-wide aggregator of resource usage data.
home: https://github.com/kubernetes-incubator/metrics-server
keywords:
- metrics-server
maintainers:
- email: gkothiyal@sgmctech.com
  name: Gaurav Kothiyal
name: metrics-server
sources:
- https://github.com/kubernetes-incubator/metrics-server
version: 2.8.2
