---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.image.name }} 
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: "service"
    app.kubernetes.io/part-of: "graylog-services"
    app.kubernetes.io/ops_team: "devops"
    app.kubernetes.io/dev_team: "graylog-services"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.image.name }}
    # namespace: {{ .Values.namespace }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{.Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 75
