{{- if .Values.ingress.enabled -}}
{{- $fullName := include "graylog.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "graylog.name" . }}
    helm.sh/chart: {{ include "graylog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: "service"
    app.kubernetes.io/part-of: "graylog-services"
    app.kubernetes.io/ops_team: "devops"
    app.kubernetes.io/dev_team: "graylog-services"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.route53_dns }}"
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: graylog-external
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.rules.path }}
            backend:
              serviceName: {{ .Values.image.name }}
              servicePort: {{ .Values.service.port }}
{{- end }}
