---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.image.name }}
    release: {{ .Release.Name }}
    heritage: "Tiller"
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: "service"
    app.kubernetes.io/part-of: "graylog-services"
    app.kubernetes.io/ops_team: "devops"
    app.kubernetes.io/dev_team: "graylog-services"
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
