apiVersion: v1
description: Merge Ingress Controller combines multiple ingress resorces into a new
  one.
home: https://github.com/jakubkulhan/ingress-merge
keywords:
- ingress
maintainers:
- email: jakub.kulhan@gmail.com
  name: Jakub Kulhan
- email: alen.komljen@live.com
  name: komljen
name: merge-ingress
version: "0.2"
