# Declare variables to be passed into your templates.

namespace: graylog
route53_dns:
acm: 
replicaCount: 1

image:
  name: graylog
  account: 
  tag: 
  pullPolicy: IfNotPresent

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: "25%"
    maxSurge: "1"

service:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "2"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "5"
  type: NodePort
  port: 80
  targetPort: 80
  protocol: TCP

ingress:
  enabled: true
  config: graylog-external
  healthcheckpath: /

resources:
  limits:
    cpu: "512m"
    memory: 1Gi
  requests:
    cpu: "256m"
    memory: 256Mi

rules:
  path: "/*"

hpa:
  minReplicas: 2
  maxReplicas: 5
  

nodeSelector: {}

tolerations: []

affinity: {}
