apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-external
  namespace: graylog
data:
  annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.acm }}
